server:
  port: 8081

spring:
  profiles:
#    active: production
    active: dev
    
#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

management:
  endpoints: 
    web:
      exposure:
        include: "*"
       
logging:
  file: ./logs/sample-boot-application.log
